"""
Django settings for djangotailwind project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from datetime import datetime


import environ
from pathlib import Path
env = environ.Env()
environ.Env.read_env()

# read the environment variable from the env
CONSUMER_KEY = env('CONSUMER_KEY')
# second optional way to read environmental variable
# for this to work define the .env in the same folder as your settings and add it in .gitignore
CONSUMER_SECRET = os.environ.get('CONSUMER_SECRET')

PASS_KEY = env('PASS_KEY')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-np!(s3fbi3cz3d$l#rid(7w=43ezh$#rf5ek2#_yw4zr%v1za9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0882-197-231-183-178.ngrok-free.app','127.0.0.1','77f5-102-140-245-169.ngrok-free.app','7b9f-102-140-245-169.ngrok-free.app','26e1-197-231-183-178.ngrok-free.app']
CSRF_TRUSTED_ORIGINS = ['https://0882-197-231-183-178.ngrok-free.app','https://77f5-102-140-245-169.ngrok-free.app','https://7b9f-102-140-245-169.ngrok-free.app',
                        'https://26e1-197-231-183-178.ngrok-free.app']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'myapp.apps.MyappConfig',
    'phonenumber_field',
    'crispy_forms',
    'crispy_bootstrap4',
    'crispy_tailwind'

]
# register the generated theme app so tha django uses it by default

TAILWIND_APP_NAME = 'theme'
#  define node.js path in your django app
NPM_BIN_PATH = 'C:/Program Files/nodejs/npm.cmd'
# specify the AUTH_USER_MODEL to be used by your custom model
AUTH_USER_MODEL = 'myapp.MyappUSer'

# crispy_forms in INSTALLED_APPS along with bootstrap4
# set boostrap4 as the default and allowed crispy template pack
CRISPY_TEMPLATE_PACK = 'tailwind'
CRISPY_ALLOWED_TEMPLATE_PACKS = 'tailwind'
# define the LOGIN_URL Constant to redirect the users once they click logout view
LOGIN_URL = 'myapp:login'
# declare the LOGIN_REDIRECT_URL constant to define the page to take user after login
LOGIN_REDIRECT_URL = 'myapp:donation'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangotailwind.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangotailwind.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# TODO:shift this code

