# Generated by Django 4.2.3 on 2023-07-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
