# Generated by Django 4.2.3 on 2023-07-11 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_myappuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='start with the country code eg +254', max_length=128, region=None),
        ),
        migrations.CreateModel(
            name='MympesaDonations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_code', models.CharField(max_length=400)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
