# Generated by Django 4.2.3 on 2023-07-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_myappuser_phone_number_mympesadonations'),
    ]

    operations = [
        migrations.AddField(
            model_name='mympesadonations',
            name='mpesa_request_body',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
