# Generated by Django 4.2.3 on 2023-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mympesadonations_mpesa_request_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mympesadonations',
            name='mpesa_request_body',
            field=models.CharField(max_length=1000),
        ),
    ]
